# Generated by Django 4.0 on 2021-12-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='updated',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='updated',
            new_name='modified',
        ),
    ]
