# Generated by Django 4.0 on 2021-12-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_updated_product_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': ' Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Category Product', 'verbose_name_plural': 'Categories Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='earn',
            field=models.SmallIntegerField(default=30),
        ),
    ]
