# Generated by Django 4.0 on 2022-01-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_alter_productcategory_options_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempurchase',
            name='earn',
            field=models.SmallIntegerField(default=30),
        ),
        migrations.AlterUniqueTogether(
            name='itempurchase',
            unique_together={('purchase', 'product')},
        ),
    ]
